const SHUOLD_DISPATCH = '@SHUOLD_DISPATCH'
const DISPATCH = '@DISPATCH'
const WILL_UPDATE = '@WILL_UPDATE'
const SHUOLD_UPDATE = '@SHUOLD_UPDATE'
const DID_UPDATE = '@DID_UPDATE'
const THROW_ERROR = '@THROW_ERROR'

export default {
	SHUOLD_DISPATCH,
	DISPATCH,
	WILL_UPDATE,
	SHUOLD_UPDATE,
	DID_UPDATE,
	THROW_ERROR
}