//life cycle key
export default {
	GET_TABLE: 'GET_TABLE',
	DISPATCH: 'DISPATCH',
	SHOULD_DISPATCH: 'SHOULD_DISPATCH',
	WILL_UPDATE: 'WILL_UPDATE',
	SHOULD_UPDATE: 'SHOULD_UPDATE',
	DID_UPDATE: 'DID_UPDATE',
	THROW_ERROR: 'THROW_ERROR',
	ASYNC_START: 'ASYNC_START',
	ASYNC_END: 'ASYNC_END',
	SYNC: 'SYNC'
}