const SHOULD_DISPATCH = '@SHOULD_DISPATCH'
const DISPATCH = '@DISPATCH'
const WILL_UPDATE = '@WILL_UPDATE'
const SHOULD_UPDATE = '@SHOULD_UPDATE'
const DID_UPDATE = '@DID_UPDATE'
const THROW_ERROR = '@THROW_ERROR'
const ASYNC_START = '@ASYNC_START'
const ASYNC_END = '@ASYNC_END'
const SYNC = '@SYNC'

export default {
	SHOULD_DISPATCH,
	DISPATCH,
	WILL_UPDATE,
	SHOULD_UPDATE,
	DID_UPDATE,
	THROW_ERROR,
	ASYNC_START,
	ASYNC_END,
	SYNC
}